In [484]:
import numpy as np
import pyreadr
import pandas as pd
from tensorflow import keras
from tensorflow.keras.models import Sequential

landcover_dict = pyreadr.read_r('data/landcover/lcv_nat.landcover.pnts_sites.rds')
landcover_frame = pd.DataFrame(landcover_dict[None])

In [444]:
landcover_matrix = pyreadr.read_r('data/landcover/lcv_nat.landcover.pnts_sites_cm.rds')
landcover_matrix_frame = pd.DataFrame(landcover_dict[None])

In [445]:
landcover_frame.head()

source_db point_id map_code_pnv map_code_glc100m  \
0  Geo-wiki_HIF  1176602          112              112   
1  Geo-wiki_HIF  1178024          112              112   
2  Geo-wiki_HIF  1177308          112              112   
3  Geo-wiki_HIF  1178266          112              112   
4  Geo-wiki_HIF  1210081          114              114   

   longitude_decimal_degrees  latitude_decimal_degrees  \
0                   -69.6543                 -6.088210   
1                    12.0307                  2.679350   
2                   -70.6701                 -9.147290   
3                   -56.2436                  0.125054   
4                    28.6030                 -8.583910   

                               publication_url  
0  https://www.nature.com/articles/sdata201775  
1  https://www.nature.com/articles/sdata201775  
2  https://www.nature.com/articles/sdata201775  
3  https://www.nature.com/articles/sdata201775  
4  https://www.nature.com/articles/sdata201775

In [446]:
landcover_matrix_frame.head()

source_db point_id map_code_pnv map_code_glc100m  \
0  Geo-wiki_HIF  1176602          112              112   
1  Geo-wiki_HIF  1178024          112              112   
2  Geo-wiki_HIF  1177308          112              112   
3  Geo-wiki_HIF  1178266          112              112   
4  Geo-wiki_HIF  1210081          114              114   

   longitude_decimal_degrees  latitude_decimal_degrees  \
0                   -69.6543                 -6.088210   
1                    12.0307                  2.679350   
2                   -70.6701                 -9.147290   
3                   -56.2436                  0.125054   
4                    28.6030                 -8.583910   

                               publication_url  
0  https://www.nature.com/articles/sdata201775  
1  https://www.nature.com/articles/sdata201775  
2  https://www.nature.com/articles/sdata201775  
3  https://www.nature.com/articles/sdata201775  
4  https://www.nature.com/articles/sdata201775

In [447]:
landcover_matrix[None]['X']

0       -69.65430
1        12.03070
2       -70.67010
3       -56.24360
4        28.60300
           ...   
69254   -72.18957
69255   -70.64320
69256   -72.54449
69257   -71.84280
69258    35.05200
Name: X, Length: 69259, dtype: float64

In [448]:
landcover_matrix[None]['Y']


0        -6.088210
1         2.679350
2        -9.147290
3         0.125054
4        -8.583910
           ...    
69254    42.535562
69255    41.549500
69256    43.613153
69257    42.269700
69258    31.347000
Name: Y, Length: 69259, dtype: float64

In [449]:
for x in landcover_matrix[None]['map_code_pnv.f'].unique():
    print(x)

X112
X114
X111
X30
X20
X124
X115
X122
X121
X90
X113
X125
X123
X60
X100
X21
X127


In [450]:
landcover_matrix[None]['mask']

0        1
1        1
2        1
3        1
4        1
        ..
69254    1
69255    1
69256    1
69257    1
69258    1
Name: mask, Length: 69259, dtype: int32

In [451]:
len(landcover_dict[None]['point_id'].unique())

67005

In [452]:
len(landcover_dict[None])

73200

In [453]:
landcover_dict[None]['map_code_glc100m'].unique()

array(['112', '114', '111', '30', '20', '124', '115', '122', '121', '90',
       '113', '125', '123', '60', '100', nan, '126', '40', '200', '80',
       '116', '50', '70'], dtype=object)

In [454]:
wa_landcover_frame = landcover_frame[(landcover_frame['longitude_decimal_degrees'] >= -125) & (landcover_frame['longitude_decimal_degrees'] <= -116)]

In [455]:
len(wa_landcover_frame)

2751

In [456]:
wa_landcover_frame['latitude_decimal_degrees'].max()

74.2606270975

In [457]:
wa_landcover_frame = wa_landcover_frame[(wa_landcover_frame['latitude_decimal_degrees'] >= 45) & (wa_landcover_frame['latitude_decimal_degrees'] <= 49)]



In [458]:
len(wa_landcover_frame)

361

In [459]:
wa_landcover_frame.head()

source_db point_id map_code_pnv map_code_glc100m  \
6639  Geo-wiki_HIF  1228643          111              111   
6672  Geo-wiki_HIF  1247093          111              111   
6685  Geo-wiki_HIF  1250169          115              115   
6702  Geo-wiki_HIF  1243472          111              111   
6706  Geo-wiki_HIF  1218208          111              111   

      longitude_decimal_degrees  latitude_decimal_degrees  \
6639                   -116.814                   48.0308   
6672                   -123.805                   47.3273   
6685                   -123.608                   45.7884   
6702                   -116.493                   47.9070   
6706                   -118.574                   48.6549   

                                  publication_url  
6639  https://www.nature.com/articles/sdata201775  
6672  https://www.nature.com/articles/sdata201775  
6685  https://www.nature.com/articles/sdata201775  
6702  https://www.nature.com/articles/sdata201775  
6706  https://www.nature.com/articles/sdata201775

In [461]:
# class_attr_unique = {0: 'unknown', 1:'forests', 2:'shurbs', 3:'herbaceous vegetation', 4:'herbaceous wetland', 5:'moss lichen',
#                           6:'bare/sparse vegetation', 7:'cropland', 8:'urban', 9:'snow and ice', 10:'permanent water bodies',
#                           11:'open sea'}
# class_attr_unique = {111: 'forests', 113: 'forests', 112: 'forests', 114: 'forests', 115: 'forests', 116: 'forests',
#                121: 'forests', 123: 'forests', 122: 'forests', 124: 'forests', 125: 'forests', 126: 'forests',
#                127: 'forests', 21: 'shurbs', 30: 'herbaceous vegetation', 90: 'herbaceous wetland', 100: 'moss lichen',
#                60: 'bare/sparse vegetation', 40: 'cropland', 50: 'urban', 70: 'snow and ice', 80: 'permanent water bodies',
#                200: 'open sea'}

class_attr_unique = {111: 1, 113: 1, 112: 1, 114: 1, 115: 1, 116: 1,
                     121: 1, 123: 1, 122: 1, 124: 1, 125: 1, 126: 1,
                     127: 1, 21: 2, 30: 3, 90: 4, 100: 5,
                     60: 6, 40: 7, 50: 8, 70: 9, 80: 10,
                     200: 11}

In [462]:
type(class_attr_unique)

dict

In [463]:
wa_landcover_frame = wa_landcover_frame.drop(['longitude_decimal_degrees', 'latitude_decimal_degrees', 'source_db', 'publication_url', 'map_code_pnv'], axis=1)

In [464]:
wa_landcover_frame = wa_landcover_frame.fillna(0)

In [465]:
wa_landcover_frame['map_code_glc100m'] = wa_landcover_frame['map_code_glc100m'].astype(str).astype(int)

In [466]:
wa_landcover_frame.replace({'map_code_glc100m': class_attr_unique}, inplace=True)

In [467]:
wa_landcover_frame['map_code_glc100m'].unique()

array([ 1,  3,  0,  7,  8, 11], dtype=int64)

In [468]:
test_one_hot = keras.utils.to_categorical(wa_landcover_frame['map_code_glc100m'], num_classes=12)

In [469]:
wa_landcover_frame['map_code_glc100m']

6639     1
6672     1
6685     1
6702     1
6706     1
        ..
73187    0
73189    0
73191    0
73192    0
73193    0
Name: map_code_glc100m, Length: 361, dtype: int64

In [470]:
wa_landcover_frame['class'] = ''

In [471]:
wa_landcover_frame

point_id  map_code_glc100m class
6639   1228643                 1      
6672   1247093                 1      
6685   1250169                 1      
6702   1243472                 1      
6706   1218208                 1      
...        ...               ...   ...
73187     1000                 0      
73189     1000                 0      
73191     1000                 0      
73192     2000                 0      
73193     1000                 0      

[361 rows x 3 columns]

In [472]:
# wa_landcover_frame = landcover_frame[(landcover_frame['longitude_decimal_degrees'] >= -125) & (landcover_frame['longitude_decimal_degrees'] <= -116)]
count = 0
for value in wa_landcover_frame['map_code_glc100m']:
    if value == 0:
        wa_landcover_frame['class'].iloc[count] = 0
    if value == 1:
        wa_landcover_frame['class'].iloc[count] = 0
    if value == 3:
        wa_landcover_frame['class'].iloc[count] = 1
    if value == 7:
        wa_landcover_frame['class'].iloc[count] = 1
    if value == 8:
        wa_landcover_frame['class'].iloc[count] = 0
    if value == 11:
        wa_landcover_frame['class'].iloc[count] = 0
    count += 1


C:\Users\mattt\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [473]:
wa_landcover_frame

point_id  map_code_glc100m class
6639   1228643                 1     0
6672   1247093                 1     0
6685   1250169                 1     0
6702   1243472                 1     0
6706   1218208                 1     0
...        ...               ...   ...
73187     1000                 0     0
73189     1000                 0     0
73191     1000                 0     0
73192     2000                 0     0
73193     1000                 0     0

[361 rows x 3 columns]

In [475]:
wa_landcover_frame['class'].value_counts()

0    346
1     15
Name: class, dtype: int64

In [490]:
wa_landcover_frame_train = test_one_hot[:300]
wa_landcover_frame_valid = test_one_hot[300:]

wa_landcover_frame_train_class = wa_landcover_frame['class'][:300]
wa_landcover_frame_valid_class = wa_landcover_frame['class'][300:]

In [535]:
first_model_landcover = Sequential()

first_model_landcover.add(keras.layers.InputLayer(input_shape = [12]))
# first_model_landcover.add(keras.layers.Dense(2, activation='relu'))
# first_model_landcover.add(keras.layers.Dense(5, activation='relu'))
first_model_landcover.add(keras.layers.Dense(1, activation='sigmoid'))

first_model_landcover.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_17 (Dense)            (None, 1)                 13        
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________


In [536]:
first_model_landcover.compile(loss='binary_crossentropy',
                              optimizer='adam',
                              metrics='accuracy')

In [537]:
first_model_landcover.fit(wa_landcover_frame_train, np.asarray(wa_landcover_frame_train_class.to_list()), epochs=25, validation_data=(wa_landcover_frame_valid, np.asarray(wa_landcover_frame_valid_class.to_list())))

Epoch 1/25
10/10 [==============================] - 0s 9ms/step - loss: 0.4940 - accuracy: 0.9600 - val_loss: 0.5250 - val_accuracy: 0.9344
Epoch 2/25
10/10 [==============================] - 0s 2ms/step - loss: 0.4870 - accuracy: 0.9600 - val_loss: 0.5182 - val_accuracy: 0.9344
Epoch 3/25
10/10 [==============================] - 0s 2ms/step - loss: 0.4800 - accuracy: 0.9600 - val_loss: 0.5116 - val_accuracy: 0.9344
Epoch 4/25
10/10 [==============================] - 0s 2ms/step - loss: 0.4732 - accuracy: 0.9600 - val_loss: 0.5052 - val_accuracy: 0.9344
Epoch 5/25
10/10 [==============================] - 0s 2ms/step - loss: 0.4664 - accuracy: 0.9600 - val_loss: 0.4988 - val_accuracy: 0.9344
Epoch 6/25
10/10 [==============================] - 0s 2ms/step - loss: 0.4598 - accuracy: 0.9600 - val_loss: 0.4925 - v

In [503]:
type(wa_landcover_frame_train[0])

numpy.ndarray

In [504]:
type(test_one_hot[0])

numpy.ndarray

In [506]:
type(wa_landcover_frame_train_class)

pandas.core.series.Series

In [508]:
wa_landcover_frame_train_class


6639     0
6672     0
6685     0
6702     0
6706     0
        ..
50504    0
50547    0
50569    0
50582    0
50590    0
Name: class, Length: 300, dtype: object

In [509]:
wa_landcover_frame_train


array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [516]:
np.asarray(wa_landcover_frame_train_class.to_list())



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])